### ISSUE TITLE
Missing Google Trends API

### ISSUE THREAD

**Issue by dfoggy00** [VincentGurgul/crypto-price-forecasting-public#1]
google_trends/config.py points to two invalid url's:

explore_url = "https://trends.google.com/trends/api/explore"
widget_url = 'https://trends.google.com/trends/api/widgetdata/multiline/csv'

It is widely understood google trends does not have a public API. Please clarify use of a google trends API.

**Comment by VincentGurgul** [comment]
Unfortunately, this repository is not actively maintained. You will need to manage its functionality independently.
